apiVersion: aperture.io.aperture.io/v1alpha1
kind: Application
metadata:
  labels:
    app.kubernetes.io/name: k8s-operator
    app.kubernetes.io/managed-by: kustomize
  name: application-sample
spec:
  image: nginx:latest
  replicas: 2
  port: 80
